### ISSUE TITLE
Deployed a cluster, scaling past 2 nodes failed, now can't start any

### ISSUE THREAD

**Issue by nathan-sav** [atlassian-labs/data-center-helm-charts#54] opened 2021-01-13 23:43 UTC
Just deployed this with following values:

- clustering.enabled: true
- postgres72 db config
- ingress true with nginx/https/tlssecretname set appropriately
- volumes.*.persistentVolumeClaim: true

This seemed to work great initially, was able to login and run through the initial setup. After this I tried scaling up to 2 nodes which also worked. Increasing to 3, the 3rd node would not start (similar errors as mentioned below).

I then tried scaling to 0 nodes, and scaling back up to 1 node and now the single node is throwing RMICachePeer listener errors and null pointer exceptions. I seem unable to start anything here now.

[jira-pod0.log](https://github.com/atlassian-labs/data-center-helm-charts/files/5811559/jira-pod0.log)

Thanks!

**Comment by kennymacleod** [comment] 2021-01-14 11:18
Hi @nathan-sav, thanks for filing the ticket. Could you include the logs of the 3rd pod also, please. I'm not aware of a problem scaling to 3 nodes (I just tried it myself to be sure). Did you use one of the versioned published charts, or did you package it from source?

**Comment by nathan-sav** [comment] 2021-01-14 18:14
I just blew away the cluster and recreated from scratch, ran into the pod 3 issue again. Full log is attached, pod2 booted fine again.
[pod3.txt](https://github.com/atlassian-labs/data-center-helm-charts/files/5816222/pod3.txt)

Just using your published chart (helm install jira atlassian-data-center/jira -n jira  -f values.yaml)

**Comment by nathan-sav** [comment] 2021-01-14 18:15
I just blew away the cluster and recreated from scratch, ran into the pod 3 issue again. Full log is attached, pod2 booted fine again.
[pod3.txt](https://github.com/atlassian-labs/data-center-helm-charts/files/5816235/pod3.txt)

Just using your published chart (helm install jira atlassian-data-center/jira -n jira -f values.yaml)

**Comment by bianchi2** [comment] 2021-01-15 04:00
Can't reproduce either. @nathan-sav what K8s installation do you have? On-prem, public cloud? Also, I'd look at where the 3rd pod is scheduled, which node? I sometimes had situations on my self made K8s cluster that pods placed onto the same node can reach each other using pod IPs. Just an assumption though.

**Comment by kennymacleod** [comment] 2021-01-15 08:51
@nathan-sav I'm thinking you may have a DB connectivity issue here. Perhaps the database hasn't been configured with enough connections, and the 3rd Jira node is hanging trying to get some.

Please note also that we have a known issue with restarting Jira pods at the moment. This happens when the restarted pod gets a different IP address to the previous pod (which is most of the time), and Jira isn't picking up the new IP correctly. This should be fixed soon.

**Comment by nathan-sav** [comment] 2021-01-15 21:54
On prem, deploying with kubespray and using the crunchydata postgres operator with pgbouncer. Interestingly, I dropped pgbouncer here and just connected directly to postgres and now I can't reproduce this (even though I don't see any limits on pgbouncer that would cause this). I'll keep digging, but does seem to be some sort of DB issue here and you can close this :)

**Closed** 2021-01-15 21:56 UTC

**Comment by bianchi2** [comment] 2021-01-16 09:24
thanks for the update @nathan-sav, and do share your feedback :)
