### ISSUE TITLE
NFS-FIXER pod starts before PVC created

### ISSUE THREAD

**Issue by jareddohrman** [atlassian-labs/data-center-helm-charts#75] opened 2021-02-03 04:08 UTC
Hi,

I ran into something rather unusual when using `nfsPermissionFixer:`

```bash
helm install -n $n jira --values values.yaml data-center-helm-charts/jira --debug
```

I noticed that the `nfs-fixer` would time out waiting for the condition

```bash
install.go:172: [debug] Original chart version: ""
install.go:189: [debug] CHART PATH: /root/data-center-helm-charts/src/main/charts/jira
client.go:268: [debug] Starting delete for "jira-nfs-fixer" Job
client.go:297: [debug] jobs.batch "jira-nfs-fixer" not found
client.go:122: [debug] creating 1 resource(s)
client.go:477: [debug] Watching for changes to Job jira-nfs-fixer with timeout of 5m0s
client.go:505: [debug] Add/Modify event for jira-nfs-fixer: ADDED
client.go:544: [debug] jira-nfs-fixer: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
client.go:505: [debug] Add/Modify event for jira-nfs-fixer: MODIFIED
client.go:544: [debug] jira-nfs-fixer: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
Error: failed pre-install: timed out waiting for the condition
helm.go:81: [debug] failed pre-install: timed out waiting for the condition
```

After scratching my head until I was bald, I noticed I could alter the pre-install value in `nfs-permission-fixer.yaml`

Before:
```yaml
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded"
```

After:
```yaml
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded"
```

This appears to have resolved one of my problems.

The second problem was the actual command run by `nfs-fixer`; if others are using an EFS backed PVC, then I found the following command in your `values.yaml` doesn't prevent Jira from starting:

```yaml
command: "chown 2001: /shared-home"
```

Hopefully, this may be of help to others encountering the same!

**Comment by bianchi2** [comment] 2021-02-15 07:26
@jareddohrman thanks for your comment. In fact, changing pre to post install may result in some race conditions where Jira pod start earlier than the permission fixer. So, while it "fixed" the problem, it's rather a workaround. I wonder what was the initial problem with the fixer pod. Was it waiting for the pvc to be bound? Did you capture k8s events?

As to nfs fixer command, uid and gid should be taken from your values.yaml, so the same runsAsUser is used for Jira and nfs fixer pods.The command is defined here https://github.com/atlassian-labs/data-center-helm-charts/blob/master/src/main/charts/jira/templates/_helpers.tpl#L84 and uid is taken from https://github.com/atlassian-labs/data-center-helm-charts/blob/master/src/main/charts/jira/values.yaml#L54

Didn't it work on EFS out of the box? In any case, it's configurable in values.yaml. I wonder if @pbruski (who played with EKS and EFS recently) has some comments. For me EFS worked just fine on OpenShift in AWS.

**Comment by pbruski** [comment] 2021-02-15 08:22
Do we have any logs from the fixer? And anyway, yes, EFS worked for out of the box, without any permission-related problems.

**Comment by kennymacleod** [comment] 2021-02-15 09:16
The fixer pod *has* to be a pre-install hook, since the products will fail to start correctly if the permissions on the shared-home volume are too restrictive. The fixer pod spec depends on the PVC being present, though, so I don't understand why it wouldn't be.

Note also that the fixer pre-install hook is optional. There's an item in `values.yaml` where you can disable it entirely. To our knowledge, the permissions bug in K8s only affects NFS shared volumes. There should be no arm in running the fixer pod for EFS, it's just that it'll have no effect.

**Comment by jareddohrman** [comment] 2021-02-15 09:39
I'm happy to try it again, but for us, the NFS-fixer pod would sit waiting for a PVC that never shows up.
```yaml
volumes:
...
  localHome:
  sharedHome:
    persistentVolumeClaim:
      create: true
      storageClassName: efs
...
```

RE permissions: it appears it only sets the group and not the user
```
drwx------ 5 jira jira 6144 Feb  2 02:09 jira/
drwxrws--x 2 root jira 6144 Feb  2 03:56 shared-home/
```
I would then get a Jira is locked show in the logs.

**Comment by jareddohrman** [comment] 2021-02-15 09:41
Also to add, we're using Jira 8.5.4/Confluence 7.4.4 (I know, old versions - but matching what we have on-premise in order for us to go-live)

**Comment by bianchi2** [comment] 2021-02-15 09:56
@jareddohrman I'd capture k8s events in your jira namespace just after helm install. I bet a PVC is sitting there in a Pending state. Is there an auto PV provisioner setup in your cluster or you manually create volumes that use efs storage class?

**Comment by jareddohrman** [comment] 2021-02-15 09:59
I let `watch kubectl get pvc` run for ~ 15 minutes with no results
`kubectl get events` showed only the nfs-fixer popping up, but nothing else
Switching `pre-` to `post-` has fixed it for us.

I may, in the future, considering creating the PVC ahead of time, and pre-loading it with the required files before a deployment (about ~1TB of files exist on our local instance)

**Comment by bianchi2** [comment] 2021-02-15 10:05
```
{{- if .Values.volumes.sharedHome.persistentVolumeClaim.create }}
```
shared home PVC template has this, and it's weird Helm did not create it first for you. I'll check it in a local cluster once again.

**Comment by bianchi2** [comment] 2021-02-17 05:38
@kennymacleod I think I reproduced it. It looks like when `Values.volumes.sharedHome.persistentVolumeClaim.create` is set to true, Helm indeed creates it before other objects that will use it, however, not for this nfs fixer pod, since it is a pre-install hook.

I have it in a pending state too (Minikube rules :) ):

```
NAME                        READY   STATUS    RESTARTS   AGE
bitbucket-nfs-fixer-jvx5n   0/1     Pending   0          4m51s
postgres-postgresql-0       1/1     Running   0          14m

Events:
  Type     Reason            Age    From               Message
  ----     ------            ----   ----               -------
  Warning  FailedScheduling  6m54s  default-scheduler  persistentvolumeclaim "bitbucket-shared-home" not found
  Warning  FailedScheduling  5m30s  default-scheduler  persistentvolumeclaim "bitbucket-shared-home" not found
```
@jareddohrman thanks for reporting it. I think most of the testing has been done with pre-provisioned PVCs and PVs.

**Comment by jareddohrman** [comment] 2021-02-17 06:26
you're welcome. Is there a step in between pre-install/post-install? ;)

**Comment by pbruski** [comment] 2021-02-17 08:10
> @jareddohrman thanks for reporting it. I think most of the testing has been done with pre-provisioned PVCs and PVs.

Isn't that the codepath that we are testing on AWS with Bitbucket?

**Comment by bianchi2** [comment] 2021-02-17 08:39
@pbruski it does not look like we use NFS permission fixer pod at all in EKS tests. We do enable it for GKE, but volumes.sharedHome.persistentVolumeClaim.create is false. No, both are never true in our tests.

The issue's easy to reproduce by setting:
```
      --set volumes.sharedHome.persistentVolumeClaim.create=true \
      --set volumes.sharedHome.nfsPermissionFixer.enabled=true
```
when running Helm upgrade. Shared home pvc is never created and nfs fixer pod is pending as expected.

**Comment by bianchi2** [comment] 2021-02-17 09:10
@jareddohrman pre-install hook in Helm means that before processing and creating any other templates, those with pre-install hook annotation are created first. Nfs fixer pod requires a shared home PVC, but Helm is going to create this PVC only after pre-hook objects are created and the nfs fixer pod had done its job :) Chicken and egg problem here.

**Comment by pbruski** [comment] 2021-02-17 09:18
Maybe we should make the permission fixer part of the Docker images?

**Comment by bianchi2** [comment] 2021-02-17 09:58
@pbruski only if the entrypoint is configurable. We don't need permission fixer too often, and for OpenShift for example it's not needed at all in most cases. Maybe an init container in a stateful set?

**Comment by pbruski** [comment] 2021-02-17 11:06
Well, as long as keep it configurable, we can make it a part of the python startup script on the image.

**Comment by dylanrathbone** [comment] 2021-03-30 03:22
Helm installs manifests based the kind priority listing defined [here](https://github.com/helm/helm/blob/release-2.10/pkg/tiller/kind_sorter.go#L29)

This means the manifests defined for the Jira chart will be installed in this order

Priority | manifest | k8s resource
------------ | -------------  | -------------
1                    | config-jvm                     | ConfigMap 
2 | configmap-fluentd       | ConfigMap
3 | shared-home-pvc        | PersistentVolumeClaim
4 | serviceaccount             | ServiceAccount
5 | service                           | Service
6 | statefulset                     | StatefulSet
7 | nfs-permission-fixer    | Job
8 | ingress                           | ingress

As @bianchi2 [mentions](https://github.com/atlassian-labs/data-center-helm-charts/issues/75#issuecomment-780413882) this is somewhat of a 🐔  & 🥚 situation... The `PersistentVolumeClaim` is one of the first resources to be created in the cluster, however, because of the `pre-install` hook defined in the `nfs-permission-fixer` the `PersistentVolumeClaim` is not created first, rather the pre-install hook is. The `pre-install` hook waits for for the `PersistentVolumeClaim` resource to become active but it never does, as a result the `nfs-permission-fixer` eventually times out.

Another potential option for getting around this is to split the chart in 2

`Chart 1:`
Priority | manifest | k8s resource
------------ | -------------  | -------------
1                    | config-jvm                     | ConfigMap 
2 | configmap-fluentd       | ConfigMap
3 | shared-home-pvc        | PersistentVolumeClaim
4 | serviceaccount             | ServiceAccount
5 | service                           | Service

Once the key dependencies are in place, run the second chart which will allow the `pre-install` hook to modify the `PersistentVolumeClaim` that was created in the first chart

`Chart 2:`
Priority | manifest | k8s resource
------------ | -------------  | -------------
6 | statefulset                     | StatefulSet
7 | nfs-permission-fixer    | Job
8 | ingress                           | ingress

Off the top of my head Im not entirely sure of the pros and cons for this approach over @pbruski suggestion: 
>make the permission fixer part of the Docker images

**Closed** 2021-04-06 22:32 UTC
