### ISSUE TITLE
Jira can't start in clustering mode in OpenShift with EBS local-home storage

### ISSUE THREAD

**Issue by bianchi2** [atlassian-labs/data-center-helm-charts#189] opened 2021-06-25 04:21 UTC
The problem was discovered in OpenShift but can be potentially reproducable in any K8s env where a Jira pod runs as unprivileged user and local home is persisted.

In an OpenShift cluster on AWS, I am using gp2 storage class. A volume is provisioned dynamically. When Jira container starts it executes an entrypoint to generate cluster.properties. It fails to [chown it](https://bitbucket.org/atlassian-docker/docker-shared-components/src/010d72fcde77a8ffa7ed3d7790f173dde9cadea5/image/entrypoint_helpers.py#lines-51):

```
INFO:root:Generating /var/atlassian/application-data/jira/cluster.properties from template cluster.properties.j2
Traceback (most recent call last):
  File "/entrypoint.py", line 23, in <module>
    gen_cfg('cluster.properties.j2', f'{JIRA_HOME}/cluster.properties',
  File "/entrypoint_helpers.py", line 64, in gen_cfg
    set_perms(target, user, group, mode)
  File "/entrypoint_helpers.py", line 34, in set_perms
    shutil.chown(path, user=user, group=group)
  File "/usr/lib/python3.8/shutil.py", line 1296, in chown
    os.chown(path, _user, _group)
PermissionError: [Errno 1] Operation not permitted: '/var/atlassian/application-data/jira/cluster.properties'
```
Jira container runs as an unprivilaged user with an OpenShift generated id. This user can write to the mounted directory. There's no reason why chown is needed in this particular case.

Is it possible to make it optional?

**Comment by nanux** [comment] 2021-07-07 07:46
This is caused by https://bitbucket.org/atlassian-docker/docker-shared-components/src/122a16186e5a861efa7a0a6244fba06c9de97e22/image/entrypoint_helpers.py#lines-64 in the Jira docker image.

@bianchi2 the override was introduced to update the `cluster.properties` file if the IP address of the node changes. Does it mean that the unprivileged user is not able to write to `/var/atlassian/application-data/jira/cluster.properties` or is the change of permissions after the write the problem?

**Comment by bianchi2** [comment] 2021-07-07 09:14
@nanux file generation is OK. chown fails after that. An unprivileged user cannot do it in OpenShift. I wonder why this chown is required at all if the file is generated by a current user in runtime, whatever this user is. So, I assume this user can read it.

**Comment by nanux** [comment] 2021-07-12 03:00
@bianchi2 we are working on it, @tarka will provide more details. It would be great if you could help test the fix on OpenShift.

**Comment by tarka** [comment] 2021-07-12 03:35
@bianchi2 There is a test image available with a fix: jira-software/8.18.0-ssmith-perm-build-1

We currently have PRs raised to get this fix in, but some testing from your end would be appreciated.

**Comment by bianchi2** [comment] 2021-07-12 06:27
@tarka @nanux I can confirm cluster.properties is being generated and Jira can start in a clustered mode now. No permission issues spotted.

**Comment by tarka** [comment] 2021-07-13 06:55
@bianchi2 Thanks for that. The PR is now merged and new builds pushed out.

**Closed by tarka** 2021-07-13 06:55 UTC
